name: Run API Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html  # Install HTML reporter

      - name: Verify Newman Installation
        run: |
          newman --version
          npm list -g --depth=0  # Check installed global packages

      - name: Create Reports Directory
        run: mkdir -p reports

      - name: Run API Tests
        run: |
          set -e
          newman run "https://api.postman.com/collections/14527260-2fc95af7-0b7a-4e2f-89a8-7f3dc2cc9c56?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          -e "https://api.postman.com/environments/14527260-5a93d38f-8c8d-42d5-b617-1bcd0f3d050e?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          --reporters cli,html --reporter-html-export reports/api-test-report.html
          
          # Debugging: Check if the file exists after Newman runs
          ls -la reports/

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Report
          path: reports/
          if-no-files-found: warn  # Don't fail if no report is found

      - name: Commit and Push Report
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "eslamsamy650@github.com"
          git config --global user.name "eslamsamy650"
          git add reports/api-test-report.html || echo "No changes to add"
          git commit -m "Add latest API test report" || echo "No changes to commit"
          git push origin main || echo "Push failed, check permissions"
