name: Run API Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html  # Install HTML reporter

      - name: Verify Newman Installation
        run: |
          newman --version
          npm list -g --depth=0  # Check installed global packages

      - name: Create Reports Directory
        run: mkdir -p reports

      - name: Run API Tests
        continue-on-error: true  # Ensure the workflow does not fail if tests fail
        run: |
          set -e
          newman run "https://api.postman.com/collections/14527260-2fc95af7-0b7a-4e2f-89a8-7f3dc2cc9c56?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          --environment "https://api.postman.com/environments/14527260-5a93d38f-8c8d-42d5-b617-1bcd0f3d050e?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          --reporters cli,html --reporter-html-export reports/api-test-report.html || true  # Prevent exit code 1 from failing the workflow
          
          # Debugging: Check if the file exists after Newman runs
          ls -la reports/

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Report
          path: reports/
          if-no-files-found: warn  # Warn instead of failing if no files are found

      - name: Commit and Push Test Report to Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use the stored Personal Access Token
        run: |
          if [ -f reports/api-test-report.html ]; then
            git config --global user.email "eslamsamy650@github.com"
            git config --global user.name "eslamsam650"
            git add reports/api-test-report.html
            git commit -m "Add latest API test report"
            git push https://eslamsamy650:${GITHUB_TOKEN}@github.com/eslamsamy650/khusm-api-tests.git main
          else
            echo "No report found, skipping commit."
